FROM php:8.2-fpm

# Instala pacotes necessários para Laravel
RUN apt-get update && apt-get install -y \
    git unzip libpng-dev libonig-dev libxml2-dev curl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instala Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

# Copia .env.example -> .env se não existir
RUN if [ ! -f .env ]; then cp .env.example .env; fi

# Instala dependências do PHP
RUN composer install --no-dev --optimize-autoloader \
    && php artisan key:generate --force

# Permissões
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]
