version: '3.9'

services:
  # --- NGINX ---
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back-end/public:/var/www/public:ro
    depends_on:
      - backend
      - dashboard
      - landing-page
    networks:
      - app-network

  # --- LARAVEL BACKEND ---
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    expose:
      - "9000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: http://localhost/api
    volumes:
      - ./back-end:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  # --- MYSQL ---
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # --- DASHBOARD (React + Vite) ---
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    restart: unless-stopped
    expose:
      - "5173"  # Porta do Vite
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=http://localhost/api  # Variável para o Vite
    volumes:
      - ./dashboard:/app  # Para hot reload em dev
      - /app/node_modules  # Evita conflito com node_modules local
    networks:
      - app-network
    depends_on:
      - backend

  # --- LANDING PAGE ---
  landing-page:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    container_name: landing_page
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_API_URL=http://localhost/api
    volumes:
      - ./landing-page/.env:/app/.env:ro
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge