version: "3.9"

services:
  # ---------------- BACKEND LARAVEL ----------------
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_backend
    volumes:
      - ./back-end:/var/www
      - ./back-end/storage:/var/www/storage
      - ./back-end/.env:/var/www/.env:ro   # monta .env se existir
    networks:
      - app-network
    depends_on:
      - mysql

  # ---------------- MYSQL ----------------
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # ---------------- DASHBOARD (React + Vite) ----------------
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_dashboard
    ports:
      - "${DASHBOARD_PORT}:80"
    volumes:
      - ./dashboard/.env:/app/.env:ro   # monta .env se existir
    networks:
      - app-network

  # ---------------- LANDING PAGE (Next.js) ----------------
  landing-page:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_landing
    ports:
      - "${LANDING_PORT}:3000"
    volumes:
      - ./landing-page/.env:/app/.env:ro   # monta .env se existir
    networks:
      - app-network

  # ---------------- NGINX ----------------
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
      - dashboard
      - landing-page
    networks:
      - app-network

# ---------------- VOLUMES ----------------
volumes:
  mysql_data:

# ---------------- NETWORK ----------------
networks:
  app-network:
    driver: bridge
