# Etapa 1 - Build
FROM node:18-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Copia .env.example -> .env se não existir
RUN if [ ! -f .env ]; then cp .env.example .env; fi

RUN npm run build

# Etapa 2 - Produção
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
