FROM node:18-alpine AS base
WORKDIR /app
COPY package*.json ./

# Etapa Dev
FROM base AS dev
RUN npm install
COPY . .

# Copia .env.example -> .env se não existir
RUN if [ ! -f .env ]; then cp .env.example .env; fi

EXPOSE 3000
CMD ["npm", "run", "dev"]

# Etapa Build
FROM base AS build
RUN npm install
COPY . .
RUN if [ ! -f .env ]; then cp .env.example .env; fi
RUN npm run build

# Etapa Produção
FROM node:18-alpine AS production
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3000
CMD ["npm", "start"]
